name: First workflow
on: 
 # pull_request:
 #   branches: 
 #     - main
  push:
    branches:
      - feature-test2

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
     - name: Clonar repositorio
       uses: actions/checkout@v4

     - name: Imprimir algo
       run: echo "hola algo"